apiVersion: v1
kind: Pod 
metadata:
  name: docker-image-build
  namespace: build
spec: 
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true


    - name: python-test
      image: python:3.9-slim
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: false

    - name: docker-compose
      image: docker/compose:latest
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: true

