version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/books"

volumes:
  mongo_data:

