# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the dependencies file to the working directory
COPY requirements.txt ./

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Install pytest
RUN pip install pytest

# Expose the port that the Flask app runs on
EXPOSE 5000

# Define environment variable for MongoDB URI (if needed)
ENV MONGO_URI mongodb://mongodb:27017/books

# Command to run the tests
CMD ["pytest"]
