# Use an official Python runtime as a parent image
FROM python:3.8.2-alpine

# Set the working directory
WORKDIR /app

# Install Git
RUN apk update && apk add --no-cache git

# Copy the dependencies file to the working directory
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the Flask app runs on
EXPOSE 5000

# Define environment variable for MongoDB URI (if needed)
ENV MONGO_URI mongodb://mongodb:27018/books

# Command to run the tests
CMD ["pytest"]
