global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    namespaces:
      names:
        - 'default'
        - 'observation'
