apiVersion: v1
kind: Service
metadata:
  name: {{ include "books.fullname" . }}
  labels:
    {{- include "books.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "books.selectorLabels" . | nindent 4 }}
