apiVersion: v1
data:
  applicationUpdateStrategies: |
    - name: books
      kind: Deployment
      # ... other application-specific configuration
      updateModes:
        - type: digest
          # ... digest update strategy options (refer to documentation)
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"applicationUpdateStrategies":"- name: books\\n  kind: Deployment\\n  # ... other application-specific configuration\\n  updateModes:\\n    - type: digest\\n      # ... digest update strategy options (refer to documentation)\\n\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":\"2024-04-21T21:51:00Z\",\"name\":\"argocd-image-updater-config\",\"namespace\":\"argocd\",\"resourceVersion\":\"9001\",\"uid\":\"0bb88e46-07d6-4615-b0af-1a0c3157e82e\"}}\n"},"resourceVersion":"9001"}
  name: argocd-image-updater-config
  namespace: argocd
  resourceVersion: "9001"  
  uid: 0bb88e46-07d6-4615-b0af-1a0c3157e82e
